<a href="https://colab.research.google.com/github/vadim-privalov/-/blob/main/%D0%9A%D0%BE%D0%BF%D0%B8%D1%8F_%D0%B1%D0%BB%D0%BE%D0%BA%D0%BD%D0%BE%D1%82%D0%B0_%22Part_1_HW_Write_our_own_library_ipynb%22.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Домашнее задание. Часть 1.

- напишем свою собственную библиотеку

Вего за эту часть ДЗ можно набрать максимум **11.5 баллов**. Разбиение баллов по каждой из задач представлено непосредственно перед текстом каждой задачи.

**Дедлайн - пятница, 11.12.2020 в 23:59.**

Дедлайн жесткий, сдача после дедлайна - 0 баллов за ДЗ.

Ссылка на ноутбук в колабе: https://colab.research.google.com/drive/1LgWtESFmiNW1WlVFCHKyNl_BxAWxoL3Z?usp=sharing

Допустим мы хотим написать фнкцию, которая складывает 2 числа и сохранить ее в отдельный .py файл. Пример:

In [1]:
%%writefile lib.py
def summ(a1, b1):
    return a1+b1

Writing lib.py


In [2]:
from lib import summ

In [3]:
summ(2,6)

8

Попробуем запустить через "терминал"

In [4]:
!python3 lib.py

Ничего не происходит. А теперь добавим `if __name__ == "__main__"` в наш код и пересохраним файл lib.py

In [5]:
%%writefile lib.py
import sys

a1 = float( sys.argv[1] ) # Считываем аргументы прямо из терминала
b1 = float( sys.argv[2] ) # Считываем аргументы прямо из терминала

def summ(a1, b1):
    return a1+b1

if __name__ == "__main__":
    print(summ(a1, b1))


Overwriting lib.py


In [6]:
!python3 lib.py 2 4

6.0


# **Задание 1**

Реализуйте следующие функции и сохраните их в библиотеку **my_math_lib.py** (пока без использования конструкции `if __name__ == "__main__"`)

**1 point** 
1. **def deg_to_rad()**. Напишите программу на Python для преобразования градусов в радианы.  *(Note: Радиан - это стандартная единица измерения угла, используемая во многих областях математики. Измерение угла в радианах численно равно длине соответствующей дуги единичного круга; один радиан чуть меньше 57,3 градуса)* **1 point**

**1 point** 
2. **def rad_to_def()**. Напишите программу Python для преобразования радианов в градусы.

**1.5 point** 
3. **def discriminant()**. Напишите программу на Python для вычисления значения дискриминанта (вспоминаем квадратные уравнения). Входные данные три числа: x, y, z (учтите что корни могут быть комлЕксными!)

**1.5 point** 
4. **def power_base_sum()**. Напишите программу на Python, чтобы вычислить сумму всех цифр основания в указанной степени.

Пример: power_base_sum(2, 100)

Выход: 115



**2 point** 
5. **def magic_square()**. Напишите программу на Python для вычисления [магического квадрата](https://ru.wikipedia.org/wiki/Магический_квадрат)

Note:

Магический, или волшебный квадрат — это квадратная таблица , заполненная числами таким образом, что сумма чисел в каждой строке, каждом столбце и на обеих диагоналях одинакова. Сумма чисел в каждой строке, столбце и на диагоналях, называется магической константой, M.

**1 point** 
6. **def mult_list()**. Напишите функцию Python для умножения всех чисел в массиве list(), (размер листа на входе произвольный)

**1 point** 
7. **def create_list()**. Напишите функцию Python для создания и вывода списка (при помощи print()), в котором значения представляют собой квадрат чисел от 1 до 30 (оба включительно).

In [7]:
 %%writefile my_math_lib.py
 # 1.1
def deg_to_rad(r):
    return r * 3.14 / 180 # формула перевода градусов в радианы

# 1.2
def rad_to_def(d):
    return d * 180 / 3.14 # формула перевода радианов в градусы

# 1.3
def discriminant(x, y, z):
    # формула дискриминанта:
    d1 = y ** 2 - (4 * x * z)
    if d1 >= 0:
        return d1
    else:
        print(d1, 'Дискриминант отрицателен.Корни квадратного уравнения комплексное число')

# 1.4
def power_base_sum(x, y):
        # возведим в степень, помещаем в интовый Лист и суммируем:
        s = sum(map(int, (list(str(x ** y)))))
        return s


# 1.5
def magic_square(m):
    return int((m * (m ** 2 + 1)) / 2)  # формула магического квадрата

# 1.6
def mult_list(myList) :
    result = 1
    for x in myList:
         result = result * x # Перемножение чисел по циклу
    return result 

# 1.7
def create_list(n): 
    n1 = ([i**2 for i in range(1, n+1)]) # создание списка квадратов чисел
    return n1
    print(n1)

Writing my_math_lib.py


In [9]:
import numpy as np
# построение магического квадрата через цикл (Через функцию не получается)
N  = 5
magic_square1 = np.zeros((N,N), dtype=int) # Создаем массив N*N и заполняем его нулями
 
n = 1
a, b = 0, N//2
 
while n <= N**2: # цикл для заполнения магического квадрата цифрами с условием проверки цифр
    magic_square1[a, b] = n
    n += 1
    newa, newb = (a-1) % N, (b+1)% N
    if magic_square1[newa, newb]:
        a += 1
    else:
        a, b = newa, newb
print(magic_square1)

[[17 24  1  8 15]
 [23  5  7 14 16]
 [ 4  6 13 20 22]
 [10 12 19 21  3]
 [11 18 25  2  9]]


# **Задание 2**
Импортируйте все методы из модуля my_math_lib.

 **0.25 point** 
 - при помощи функции **def discriminant()** посчитайте дискриминант следующего уравнения: 
 $x^{2}+3 x+4=0$

**0.25 point** 
 - постройте магический квадрат размера 5х5

In [ ]:
from my_math_lib import *



In [ ]:
discriminant(1, 3, 4)

-7 Дискриминант отрицателен.Корни квадратного уравнения комплексное число


In [ ]:
magic_square(5)

65

# **Задание 3**

**2 point**
* Добавьте в вашу библиотеку конструкцию `if __name__ == "__main__"`, которая должна принимать одну из вышеперечисленных функций. 
* Важно! аргументы, подаваемые в функцию, должны подаваться напряму через терминал (как в примере)! Используйте для этого библиотеку `sys`

In [10]:
%%writefile my_math_lib.py
import sys

r = float( sys.argv[1] ) # Считываем аргументы прямо из терминала


def deg_to_rad(r):
    return r * 3.14 / 180 # формула перевода градусов в радианы

def rad_to_def(d):
    return d * 180 / 3.14 # формула перевода радианов в градусы

def discriminant(x, y, z):
    d1 = y ** 2 - (4 * x * z) # формула дискриминанта:
    if d1 >= 0:
        return d1
    else:
        print(d1, 'Дискриминант отрицателен.Корни квадратного уравнения комплексное число')

def power_base_sum(x, y):
        s = sum(map(int, (list(str(x ** y))))) # возведим в степень, помещаем в интовый Лист и суммируем:
        return s


def magic_square(m):
    return int((m * (m ** 2 + 1)) / 2)  # формула магического квадрата

def mult_list(myList) :
    result = 1
    for x in myList:
         result = result * x # Перемножение чисел по циклу
    return result 

# 1.7
def create_list(n): 
    n1 = ([i**2 for i in range(1, n+1)]) # создание списка квадратов чисел
    return n1
    print(n1)

if __name__ == "__main__":
    print(deg_to_rad(r))

Overwriting my_math_lib.py


In [ ]:
# Пример вызова функции - Вы можете вызвать любую другую
!python3 my_math_lib.py 3, 4, 5 # Например если в __main__ вы указали def discriminant()

Traceback (most recent call last):
  File "my_math_lib.py", line 3, in <module>
    x = float( sys.argv[1] ) # Считываем аргументы прямо из терминала
ValueError: could not convert string to float: '3,4,5'


In [11]:
!python3 my_math_lib.py 45 # перевод градусов в радианы

0.785
